# Generated by Django 3.1.6 on 2021-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('cust_first_name', models.CharField(max_length=30)),
                ('cust_last_name', models.CharField(max_length=30)),
                ('cust_address', models.CharField(max_length=75)),
                ('cust_zip', models.CharField(max_length=5)),
                ('cust_change_in_purchase_status', models.CharField(choices=[('New', 'New'), ('Cancelled', 'Cancelled')], max_length=15)),
                ('prod_id', models.IntegerField()),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_purchase_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mod_date', models.DateTimeField()),
            ],
        ),
    ]
