# Generated by Django 3.1.6 on 2021-02-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_repo', '0002_auto_20210212_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_change_in_purchase_status',
            field=models.CharField(choices=[('new', 'new'), ('cancelled', 'cancelled')], max_length=15),
        ),
    ]
