# Generated by Django 3.1.6 on 2021-02-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_repo', '0003_auto_20210213_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_change_in_purchase_status',
            field=models.CharField(choices=[('new', 'new'), ('canceled', 'canceled')], max_length=15),
        ),
    ]
